[package]
name = "crust"
version = "0.0.1"
authors = ["Simon Schneemelcher <schneemelchercom@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
crossterm = "0.26.0"
clap = { version = "4.1.6", features = ["derive"] }
